### ISSUE TITLE
Provide Slovenian dataset on spending data, together with explanation of fields

### ISSUE THREAD

**Issue by ocorcho** [TBFY/spending-data#1]
The Slovenian data that is being used to show anomalies should be provided in the data folder of this repository, together with a brief explanation of the fields used in the corresponding CSV

**Comment by MatejKovacic** [comment]
Slovenian spending data are available to download here:
https://erar.si/static-data/

Description of data is at Sintef Sharepoint:
Home > Work > Deliverables > D3.2 Common spending templates framework v1 > [Description_of_Erar_dataset.pdf](https://sintef.sharepoint.com/:b:/r/teams/work-2368/Shared%20Documents/Work/Deliverables/D3.2%20Common%20spending%20templates%20framework%20v1/Description_of_Erar_dataset.pdf?csf=1)

**Comment by ocorcho** [comment]
@fyedro Can you please make this data available in the repository, if allowed by license, and also extract the dataset description referred to by @MatejKovacic into a simple markdown document, for being self-contained?

**Comment by MatejKovacic** [comment]
This data is completely open, however, licence is not published on a website.

**Comment by fyedro** [comment]
I have uploaded the dataset to the "/data" folder and updated the readme file including the description of the dataset and a little example of the content which the first three rows are displayed in

**Comment by ocorcho** [comment]
Done at commit 0ea9278
